name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint Python code with flake8
      run: |
        flake8 --config=.flake8 --statistics --count

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install HTML5 and CSS linters
      run: |
        npm install html5validator stylelint stylelint-config-standard

    - name: Lint HTML with html5validator
      run: npx html5validator --root . --ignore-re="Attribute “allow” not allowed on element “iframe” at this point"

    - name: Lint CSS with stylelint
      run: npx stylelint "**/*.css"
